### ISSUE TITLE
Exokit Desktop Resizing

### ISSUE THREAD

**Issue by chrisplatorres** [exokitxr/exokit#1024]
**Describe the bug**
What happened, and what did you expect to happen?
  
I opened Exokit then maximized the window, I expected the content to not be blurry after maximizing the window.
 
 
**To Reproduce**
1. Start Exokit
2. Maximize Exokit window to 1920x1080

**System information:**
Windows 10
Built from source
`user-parallel`
Node v11.6.0
Npm v 6.5.0-next.0

**Screenshots**
![f001Capture](https://user-images.githubusercontent.com/29695350/57268819-eac23e00-704a-11e9-97af-2241a30fd169.PNG)
![f002Capture](https://user-images.githubusercontent.com/29695350/57268818-eac23e00-704a-11e9-9de4-1a2b9d8b23ce.PNG)
![f003Capture](https://user-images.githubusercontent.com/29695350/57268817-eac23e00-704a-11e9-9358-02d4385f7e45.PNG)

**Comment by modulesio** [comment]
The reason for this is that we do not resize the fake headset along with the window.

I'm working on a solution to this in the studio.

Note that this is in _some ways impossible to fix_ -- headsets have a fixed size and cannot be resized at runtime, and then the user code renders based on that.

We can however probably close the old XR session and start a new one -- provided the user code is responsive to closure and restart of the xr session.

**Comment by modulesio** [comment]
There is an option in the studio to set the metrics of the headset now:

![Capture 26](https://user-images.githubusercontent.com/6926057/57370464-36194100-715e-11e9-925d-47931e5a024c.PNG)

It currently defaults to `1080p` but we can default it as high as we want, and automatically resize it if the window resizes in fake vr display mode.

Set sufficiently high, there is no pixel stretching during the blit back to the window.

Closing this because
1. `realitytabs.html` will be removed in favor of `studio.html`, with reality tabs being another `example/`
1. the controls are in place to solve it in the studio now

**Comment by modulesio** [comment]
([The `studio` branch is over here](https://github.com/exokitxr/exokit/pull/1002))
