### ISSUE TITLE
window.location.reload() does not reload

### ISSUE THREAD

**Issue by modulesio** [exokitxr/exokit#434]
![capture3](https://user-images.githubusercontent.com/6926057/45195725-f6910280-b226-11e8-95ab-780632a38e59.PNG)

**Comment by ngokevin** [comment]
Navigation in general isn't working. Here's a test case of a page that automatically navigates from A-Frame Hello World to A-Painter: https://sticky-bull-1.glitch.me/

On a root window, the window will just disappear.

I think need to implement I-Frame navigation to handle differently as well. It keeps the original site in one native window (although maybe not running) and opens up a new native window with the new site.

Poking around on it.

**Comment by modulesio** [comment]
Yeah, it most likely regressed (wasn't being tested 🤕).

VR link handoff definitely was working ~a month ago, for the non-iframe case at least.

The `navigate` event is the central orchestrator of this I believe: https://github.com/webmixedreality/exokit/blob/b239909ca5356eca725db257665389ea9428f6be/src/core.js#L1530

**Comment by ngokevin** [comment]
This probably is not the correct fix, but wanted to check if you had a better idea. 

When navigating, there's the `originalWindow` and exokit.load will create a `newWindow`. Before, `originalWindow` was `unload`ing and clearing its timeout (which stops the render loop, killing the application) before the `newWindow` could get set up. This change makes it so that we wait for the `newWindow` to set up before unloading the `originalWindow` (the `glconstruct` event is just messing around, not the final place I'd put it).

https://sticky-bull-1.glitch.me/

So that works. The new window opens (a-painter) then the original window closes (hello, world). Though it's weird that there are two native windows showing up, wonder if we could get it to do it in place (stop rendering, then load in the new window binded to the same native window).

```
diff --git a/src/core.js b/src/core.js
index 0613791..fe54705 100644
--- a/src/core.js
+++ b/src/core.js
@@ -1525,8 +1525,11 @@ const _makeWindow = (options = {}, parent = null, top = null) => {
         dataPath: options.dataPath,
       })
         .then(newWindow => {
-          window._emit('beforeunload');
-          window._emit('unload');
+          newWindow.document.on('glconstruct', () => {
+            window._emit('beforeunload');
+            window._emit('unload');
+          });
+
           window._emit('navigate', newWindow);

           _destroyTimeouts(window);
diff --git a/src/index.js b/src/index.js
index 452ecdf..de17515 100755
--- a/src/index.js
+++ b/src/index.js
@@ -251,6 +251,8 @@ nativeBindings.nativeGl.onconstruct = (gl, canvas) => {
       gl.destroy();
     });

+    document._emit('glconstruct');
+
     return true;
   } else {
     return false;
```

**Comment by modulesio** [comment]
It seems the problem is the detection for "no more windows, we are done".

If there are still windows (and it seems there always are in this case, we don't unload until the new window at least exists) then we should probably be continuing with the renderloop.

**Comment by ngokevin** [comment]
Alright.

Is there a way to have just one native window so it seems more seamless? At the moment, it pops up a second one then closes the first one.

**Comment by modulesio** [comment]
We need to reset the context somehow for this case, and  I don’t see any way in glfw: http://www.glfw.org/docs/latest/group__context.html

Some options:

- Rewrite to some other window system
- Better align the windows
- Review and intercept every gl function to track resources locally and write a reset method that deletes and clears all state
- Rethink the concept of windows entirely, and create only a single window that receives blits from other contexts

Perhaps the last one is the easiest approach, but it would be non-negligible engineering effort.

**Comment by modulesio** [comment]
Fixed with https://github.com/exokitxr/exokit/pull/1048, in `user-parallel`, which has a totally different context tracking strategy.
